# Generated by Django 3.1.2 on 2020-10-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=700)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
