# Generated by Django 3.1.2 on 2020-10-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='page',
            name='video',
            field=models.FileField(default='', upload_to='blog/video'),
        ),
    ]
