# Generated by Django 3.1.2 on 2020-10-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201029_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='TypeBlog',
            field=models.IntegerField(default=0),
        ),
    ]
