# Generated by Django 3.1.2 on 2020-11-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page_typeblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='desc1',
            field=models.CharField(default='', max_length=700),
        ),
    ]
