# Generated by Django 3.1.2 on 2020-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_page_desc1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Call', models.IntegerField(default=0, max_length=14)),
                ('desc', models.CharField(max_length=1100)),
            ],
        ),
    ]
