# Generated by Django 3.1.2 on 2020-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='Call',
            field=models.IntegerField(),
        ),
    ]
