# Generated by Django 3.1.2 on 2020-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201118_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contect',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
